version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - "xpack.security.enabled=false"
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=\"*\""
    ports:
      - "9200:9200"
    networks:
      - elasticnet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - "5601:5601"
    networks:
      - elasticnet
    depends_on:
      - elasticsearch

networks:
  elasticnet:
    driver: bridge

